### ISSUE TITLE
Aligning consecutive slices

### ISSUE THREAD

**Issue by EmilieDel** [google-research/sofima#3] opened 2022-04-22 12:52 UTC
Hello, 

### Use case 

I have an input volume that is a reconstruction of 2D slices into a 3D volume. Therefore, the consecutive slices are jagged and the volume along perpendicular directions are not smooth. My idea is to try to align consecutive slices of that volume. 

### Code

To achieve that, I tried to use this package. Here is the snippet code I am using. 
1. **Could you tell me if I am using your repository right?** 
2. **Do you have some advices concerning the different parameters (`patch_size`, `step`, `stride`, `overlap`, ...) along this pipeline**? 

```python
from sofima.flow_field import JAXMaskedXCorrWithStatsCalculator
from sofima.flow_utils import clean_flow
from sofima.warp import ndimage_warp

patch_size = 15
step = 1
overlap = 3

maskcorr = JAXMaskedXCorrWithStatsCalculator()
flow = maskcorr.flow_field(img1, img2, patch_size, step)
clean_output = clean_flow(
    flow, 
    min_peak_ratio=np.min(flow[2]), 
    min_peak_sharpness=np.min(flow[1]), 
    max_magnitude=0, 
    max_deviation=0,
)
warped_img = ndimage_warp(
    img2, 
    clean_output, 
    stride=(step, step), 
    work_size=(patch_size, patch_size), 
    overlap=(overlap, overlap)
)
```

### Results

I would like to apply this snippet of code iteratively. Concretely, this means:
a. Alignment between `slice n` and `slice n+1` -> warping of `slice n+1`
b. Alignment between **warped** `slice n+1` and `slice n+2` -> warping of `slice n+2`
c. Alignment between  **warped** `slice n+2` and `slice n+3` -> ...

However, currently, applying this iterative procedure is giving strange results: pixels are disappearing, see images below.
![image](https://user-images.githubusercontent.com/47669575/164717941-55fa5a2d-c4de-4f5e-b36a-81b3cec3fd03.png)
3. **Do you have an idea why this is happening?** 

Thank you for your help.

**Comment by mjanusz** [comment] 2022-04-27 13:52
Hi, thanks for the detailed description of your approach! The high-level idea is a good one and similar to how we and others align e.g. thin-section EM data. I suspect what might need some adjustments are the hyperparameters. I'm not sure how large your images are, but I'm going to guess hundreds of pixels or more. With this in mind, I'd suggest:
1) Trying slightly large patch_size and larger step sizes. Step sizes that tend to work well are patch_size // 2 or patch_size // 4.
2) Visualizing the estimated flow field (you can e.g. just use plt.matshow(flow[0, ...] for the X component) to see if the estimated flow field is behaving roughly as expected. It should be generally smooth.
3) Any irregularities you see in the previous step, you should be able to remove with clean_flow. Start e.g. with min_peak_ratio = min_peak_sharpness = 1.1 and increase them until the filtered flow does not have any obviously incorrect values. If the flow is good to begin with, you can just drop the metadata channels: clean_output = flow[:2, ...]
4) If there are any missing flow entries after filtering, try regularizing it with an elastic mesh:

```
config = mesh.IntegrationConfig(dt=0.001, gamma=0., k0=0.01, k=0.1, stride=stride,
                                num_iters=1000, max_iters=20000, stop_v_max=0.001,
                                dt_max=100, prefer_orig_order=True,
                                start_cap=0.1, final_cap=10)
x = np.zeros_like(clean_output)
x _, _ = np.array(mesh.relax_mesh(x, -clean_output, config))
```

5) Warp data with `x` instead of `clean_output` (visualize it first to make sure it looks smooth as expected). For warping, unless your images are very large, you can use work_size = <image_size> and overlap = 0,0, or at least a work_size that is much larger than the patch_size used for flow estimation. The two parameters are unrelated, and work_size only impacts memory usage and parallelism.

I'm guessing that the disappearing pixels in your case are caused by invalid flow entries -- the mesh relaxation I suggested above should allow you to get rid of it.

**Comment by mjanusz** [comment] 2023-01-12 21:37
Closing for now since there don't seem to be any further updates.

**Closed by mjanusz** 2023-01-12 21:37 UTC
